### PR TITLE
Language select

### PR DESCRIPTION
**Pull request by n8snyder**
Add a language select to nav bar. This will be used to allow the user select their preferred language and have text on the site be translated to that language.

As part of this change, refactored how language data is stored to make use of Django's [translation](https://docs.djangoproject.com/en/dev/topics/i18n/translation) functionality.

### CODE REVIEW

**Comment by mikeubell** [comment]
Is there something I need to do to enable translation?  I am running the branch and the language select is there but seems to have no effect.

**Comment by adborden** [comment]
This PR is part of https://github.com/openoakland/dos-census-events/issues/29

@n8snyder, to @mikeubell's point, there's no translations yet. Should we hide the language select until we have some translations?

**Comment by mikeubell** [comment]
Yes, if the option does not do anything then we don't want to display it.  I poked around in the Django docs a bit and it seems there are some coding rules we should follow if we want to localize things properly.   I will put this option on the list of things to discuss with Ashley.

**Comment by n8snyder** [comment]
I installed [Django Waffle](https://waffle.readthedocs.io/en/stable/) to deal with hiding features. The language select form can be made available by creating a flag in the database with name "language_select".

**Comment by n8snyder** [comment]
Closing due to no longer a required feature

**Pull request closed without merging**
